# Generated by Django 5.0.9 on 2026-08-27 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIRequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(choices=[('onboarding_chat', 'Onboarding chat'), ('onboarding_extract', 'Onboarding extraction'), ('generate', 'Lyric generation'), ('rhymes', 'Rhyme suggestions'), ('other', 'Other')], default='other', max_length=30)),
                ('model', models.CharField(max_length=100)),
                ('month', models.CharField(db_index=True, max_length=7)),
                ('prompt_tokens_estimate', models.PositiveIntegerField(default=0)),
                ('completion_tokens_estimate', models.PositiveIntegerField(default=0)),
                ('succeeded', models.BooleanField(default=True)),
                ('error_message', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_requests', to='accounts.profile')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['profile', 'month'], name='airequest_profile_month_idx')],
            },
        ),
    ]
