# Generated by Django 5.0.9 on 2026-08-27 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paystack_event_id', models.CharField(max_length=255, unique=True)),
                ('event_type', models.CharField(max_length=100)),
                ('payload', models.JSONField()),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_events', to='accounts.profile')),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paystack_customer_code', models.CharField(max_length=255, unique=True)),
                ('paystack_subscription_code', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('paystack_email_token', models.CharField(blank=True, max_length=255)),
                ('paystack_plan_code', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('incomplete', 'Incomplete'), ('active', 'Active'), ('non_renewing', 'Non-renewing (cancels at period end)'), ('attention', 'Needs attention (payment issue)'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='incomplete', max_length=20)),
                ('current_period_end', models.DateTimeField(blank=True, null=True)),
                ('cancel_at_period_end', models.BooleanField(default=False)),
                ('unit_amount_cents', models.PositiveIntegerField(default=0, help_text="Price per billing interval, in the currency's subunit (e.g. kobo for NGN).")),
                ('currency', models.CharField(blank=True, default='NGN', max_length=10)),
                ('billing_interval', models.CharField(blank=True, default='monthly', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='accounts.profile')),
            ],
        ),
    ]
