# Generated by Django 5.0.9 on 2026-08-27 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoundBible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('themes', models.JSONField(blank=True, default=list)),
                ('vocabulary', models.CharField(blank=True, max_length=500)),
                ('imagery', models.CharField(blank=True, max_length=500)),
                ('rhyme_habits', models.CharField(blank=True, max_length=500)),
                ('structure_habits', models.CharField(blank=True, max_length=500)),
                ('tone_default', models.CharField(blank=True, max_length=500)),
                ('influences', models.JSONField(blank=True, default=list)),
                ('freeform', models.TextField(blank=True)),
                ('onboarded', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sound_bible', to='accounts.profile')),
            ],
            options={
                'verbose_name': 'Sound Bible',
                'verbose_name_plural': 'Sound Bibles',
            },
        ),
    ]
